config/routes.rb
Helpdesk::Application.routes.draw do
  resources :tickets
  root :to => "tickets#index"

end

app/models/email_processor.rb
class EmailProcessor
  def self.process(email, ticket)
  	@ticket = ticket
    @ticket.update!(ticket_id, answer: message.body.decoded)
  end
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  attr_accessible :description, :name

  def self.update_from_postmark(mitt)
    id = mitt.subject.split("-").first.split(":").last.to_i
    ticket = Ticket.find_by_id(id)

    if ticket
      ticket.helpdesk_response = mitt.text_body
      ticket.save
    else
      return false
    end
  end
end

app/controllers/api/tickets_controller.rb
class Api::TicketsController < ApplicationController
  skip_before_filter :verify_authenticity_token

  def create

    if Ticket.update_from_postmark(Postmark::Mitt.new(request.body.read))
      render text: "Response received", status: :created
    else
      render text: "Unauthorized", status: :Unauthorized
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  # GET /tickets
  # GET /tickets.json
  def index
    @tickets = Ticket.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tickets }
    end
  end

  # GET /tickets/1
  # GET /tickets/1.json
  def show
    @ticket = Ticket.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @ticket }
    end
  end

  # GET /tickets/new
  # GET /tickets/new.json
  def new
    @ticket = Ticket.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @ticket }
    end
  end

  # GET /tickets/1/edit
  def edit
    @ticket = Ticket.find(params[:id])
  end

  # POST /tickets
  # POST /tickets.json
  def create
    @ticket = Ticket.new(params[:ticket])

    respond_to do |format|
      if @ticket.save
        TicketMailer.new_ticket(@ticket).deliver
        format.html { redirect_to @ticket, notice: 'Ticket was successfully created.' }
        format.json { render json: @ticket, status: :created, location: @ticket }

      else
        format.html { render action: "new" }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tickets/1
  # PUT /tickets/1.json
  def update
    @ticket = Ticket.find(params[:id])

    respond_to do |format|
      if @ticket.update_attributes(params[:ticket])
        format.html { redirect_to @ticket, notice: 'Ticket was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tickets/1
  # DELETE /tickets/1.json
  def destroy
    @ticket = Ticket.find(params[:id])
    @ticket.destroy

    respond_to do |format|
      format.html { redirect_to tickets_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Helpdesk</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= link_to "Home", tickets_path %><br>

  <% flash.each do |key, value| %>
    <%= value %>
  <% end %>

<%= yield %>

</body>
</html>

app/views/tickets/_form.html.erb
<%= form_for(@ticket) do |f| %>
  <% if @ticket.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ticket.errors.count, "error") %> prohibited this ticket from being saved:</h2>

      <ul>
      <% @ticket.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description, :rows => 5%>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tickets/edit.html.erb
<h1>Editing ticket</h1>

<%= render 'form' %>

<%= link_to 'Show', @ticket %> |
<%= link_to 'Back', tickets_path %>

app/views/tickets/index.html.erb
<h1>Listing tickets</h1>

<table>
  <tr>
  	<th>Ticket Number</th>
    <th>Ticket Name</th>
  </tr>

<% @tickets.each do |ticket| %>
  <tr>
  	<td><%= ticket.id %></td>
    <td><%= link_to ticket.name, ticket %></td>

  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Ticket', new_ticket_path %>

app/views/tickets/new.html.erb
<h1>New ticket</h1>

<%= render 'form' %>

<%= link_to 'Back', tickets_path %>

app/views/tickets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @ticket.name %>
</p>

<p>
  <b>Description:</b>
  <%= @ticket.description %>
</p>
<p>
  <b>Answer:</b>
  <%= @ticket.answer %>
</p>



<%= link_to 'Edit', edit_ticket_path(@ticket) %> |
<%= link_to 'Destroy', @ticket, method: :delete, data: {confirm: 'Are you sure?' } %> |
<%= link_to 'Back', tickets_path %>